name: Generate ASCII Artwork

on: push

jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2
            
            - name: List Repo Files
              run: ls -ltra
            
            - name: Executing Shell Script
              run: |
                chmod +x ascii.sh
                ./ascii.sh
                sleep 30
    
    test_job:
        runs-on: ubuntu-latest
        steps:            
            - name: Sleep for 10 Sec
              run: sleep 10
            - name: Test File Exists
              run: grep -i "dragon" dragon.txt
            
    
    deploy_job:
        runs-on: ubuntu-latest
        steps:
            - name: Read File
              run: cat dragon.txt
            
            - name: Deploy
              run: echo "Deploying ......."

