name: Generate ASCII Artwork

on:
  workflow_dispatch:
        
    # schedule:
    #   - cron: "*/1 * * * *"
  #  push

jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2
            
            - name: List Repo Files
              run: ls -ltra
            
            - name: Executing Shell Script
              run: |
                chmod +x ascii.sh
                ./ascii.sh
            
            - name: Upload Dragon File
              uses: actions/upload-artifact@v4
              with:
                name: dragon-file
                path: dragon.txt
    
    test_job:
        runs-on: ubuntu-latest
        needs: build_job
        steps:            
            - name: Download Dragon File
              uses: actions/download-artifact@v4
              with:
                  name: dragon-file

            - name: Test File Exists
              run: grep -i "dragon" dragon.txt
            
    
    deploy_job:
        runs-on: ubuntu-latest
        timeout-minutes: 1
        concurrency: 
          group: production-deployment
          cancel-in-progress: true
        needs: [test_job,build_job]
        steps:
            - name: Download Dragon File
              uses: actions/download-artifact@v4
              with:
                  name: dragon-file
                  
            - name: Read File
              timeout-minutes: 1
              run: |
                cat dragon.txt
                sleep 600
            
            - name: Deploy
              run: echo "Deploying ......."

